name: Cypress Tests

on:
  push:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Start Vite app
      - name: Start app
        run: npm run dev &

      # Wait until app is ready
      - name: Wait for app
        run: npx wait-on http://localhost:5173

      # Run Cypress with Cloud recording
      - name: Run Cypress Tests (Cloud)
        run: npx cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }}